### PR TITLE
Refactored readme

### PR DESCRIPTION
**Pull request by OdineiRibeiro**
* Change README extention to `.md` to accept markdown notation
* Refactored README links
* Added title

### CODE REVIEW

**Comment by gregkrsak** [comment]
No broken links.

**Comment by OdineiRibeiro** [comment]
Hello @gregkrsak!
Isn't about broken links. I've formatted links in the github markdown style to have a better look in the project!

**Comment by gregkrsak** [comment]
I understand. I meant to communicate that I reviewed the links (as I would in any review) and none of them are broken.

**Comment by OdineiRibeiro** [comment]
@gregkrsak, i'm sorry :sweat_smile:

**Comment by sethwoodworth** [comment]
Can confirm that the edit formats markdown correctly and strips some whitespace.  Merging.

**Pull request merged**
